### PR TITLE
Feature/url title improve

### PR DESCRIPTION
**Pull request by dminchev**
This change will solve the problem with bad materialized_path generation for pages with title in different than latin chars.

I'm using babosa gem with currently supports the following languages:
- bulgarian
- cyrillic
- danish
- german
- greek
- latin
- macedonian
- norwegian
- romanian
- russian
- serbian
- spanish
- swedish
- ukrainian
- vietnamese

In order to use activate some of the languages different from latin you have to specify in initializer similar to locales:

```ruby
Spina.configure do |config|
  config.transliterations = %i(latin bulgarian german)
end
``` 

Also I've created a fallback behavior if the title parameterization fails to build the slug based on the page id 

```ruby
"page-#{id}"
```

Here is reference to issues with materialized_path #348 #220 

Hope you find this useful!

### CODE REVIEW

**Comment by Bramjetten** [comment]
What does this offer that `parameterize` does not?

**Comment by dminchev** [comment]
Title in languages with different from latin chars don't generate proper path

```
[1] pry(main)> "Тест".parameterize
=> ""
[2] pry(main)> "Test".parameterize
=> "test"
```
with this changes the string will be translated to proper url friendly latin chars or will fallback to page-id

**Comment by Bramjetten** [comment]
Do we have to define all transliterations in a config file? Can't we just add all available transliterations?

**Comment by dminchev** [comment]
I don't think it will be a problem to add by default all, however I've checked similar configs for friendly-id and non latin title and they follow this pattern. 
My personal opinion is to list just the ones you need.

**Comment by Bramjetten** [comment]
If we merge this, the default should be that no changes are required for existing projects. Anyone who wants to add transliterations could do so using this config. Perhaps we could add some comments in Spina's config file as an example.

**Comment by dminchev** [comment]
Fair enough, I think that running install would add the default latin from the template. However this is additional action to the devs. I'll add default latin in the config so it won't require any other actions for the existing projects.

```
rails g spina:install
```

Will add it to the readme.

**Comment by dankmitchell** [comment]
@dminchev I think this is a great improvement, can you replace to fix conflicts and add a note into he readme.

**Comment by Bramjetten** [comment]
Is this still a wanted feature?

**Comment by Bramjetten** [comment]
I'm going to assume this is still a wanted feature. Since it's quite an old PR it'll need some editing. @dminchev cool if I pick this up?

**Review by Bramjetten — APPROVED** [review]

**Comment by Bramjetten** [comment]
I'm sorry for taking so long, but it's merged now! ✌️

**Comment by dminchev** [comment]
> I'm going to assume this is still a wanted feature. Since it's quite an old PR it'll need some editing. @dminchev cool if I pick this up?

Yeah sure, thanks!

**Pull request merged**
