### PR TITLE
Remove search and analytics

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
Analytics and google verification would rarely change so it doesn't need maintaining in the CMS.

### Changes proposed in this pull request
Remove analytics, site verification and robots.txt 

### Guidance to review
🚢

### CODE REVIEW

**Comment by Bramjetten** [comment]
Can you remove the locales from this PR?

**Comment by dankmitchell** [comment]
@Bramjetten do you mean the white space changes?

**Comment by Bramjetten** [comment]
Yes, because they'll be introduced again after pulling new locales.

**Comment by Bramjetten** [comment]
@dankmitchell Same thing here

**Pull request closed without merging**
