### PR TITLE
Save all pages after updating resource

### LINKED ISSUE #714: changing resource slug does not update existing pages
When changing the slug of a resource via the settings UI, existing pages of that resource are not updated.

### PR DESCRIPTION
**Pull request by kahrpatrick**
### Context
Fixes #714 

### Changes proposed in this pull request
Update all pages of a resource when it is saved to make sure the materialized path is updated.

### CODE REVIEW

**Comment by Bramjetten** [comment]
I think this is a good idea, but I prefer a different implementation. Can we move this to a bg job? I have projects with several resources containing 1.000+ pages

**Comment by kahrpatrick** [comment]
Sure, we could set it up as a job. Ideally this would require an external queuing backend to prevent inconsistencies in case of a crash. What do you think about this?

**Comment by Bramjetten** [comment]
I think we could just create an ActiveJob and let the end user/developer decide which queuing backend they want to use. Kinda like how ActiveStorage creates activejobs for analyzing and purging files.

**Comment by kahrpatrick** [comment]
Implemented as a job now.

**Comment by Bramjetten** [comment]
Thanks! 

I've added configurable queues to Spina. You can configure how to queue these jobs:

```ruby
Spina.configure do |config|
  config.queues.page_updates = :your_queue
end
```

It defaults to your queue adapter's default.

**Comment by Bramjetten** [comment]
I've also changed the callback to `after_commit`. Sidekiq is sometimes too fast otherwise!

**Comment by kahrpatrick** [comment]
Thanks, makes sense.

**Review by Bramjetten — APPROVED** [review]

**Comment by Bramjetten** [comment]
@kahrpatrick Thanks for your work!

**Pull request merged**
