### PR TITLE
Add active_list_item_css to Menu Presenter

### PR DESCRIPTION
**Pull request by sarabpj**
### Context
 @Bramjetten had a conversation with @mweitzel in discord about adding styles to the list item in Menu Presenter that matches current page. 

### Changes proposed in this pull request
Add `active_list_item_css` that applies config styles to list item that matches current page

### CODE REVIEW

**Comment by Bramjetten** [comment]
Thank you for this PR!

I see you've only added an active class to the current page. It might be useful to style parent pages differently as well.
How about `active_list_item_css` for all ancestors, and `current_list_item_css` for the current page?

Comparing all ancestors to the current page would create N+1 queries though, so then it might be better to compare to the current path to `materialized_path` instead.

**Comment by sarabpj** [comment]
@Bramjetten  just to make sure I understand the request correctly `active_list_item_css ` should apply a class on the body of the current page?

**Comment by Bramjetten** [comment]
@sarabpj Imagine a navigation tree like this:

- Home
- About
- - Company
- - History

When visiting /about/history, `active_list_item_css` should apply a class to the About page, and `current_list_item_css` should apply a class to the History page.

**Comment by sarabpj** [comment]
Hey @Bramjetten I went ahead and made the changes you requested please let me know if there is anything else.

**Comment by Bramjetten** [comment]
Thanks for your updates! 🙏

You're currently using `ancestry` to check parent pages. While this definitely works, it also creates a lot of SQL-queries. Especially in a large menu. I'd prefer to compare the materialized path instead. That way we don't have to fetch all parents recursively.

Maybe something like this would suffice:

```ruby
def parent_of_current?(item)
  return false if item.homepage?
  Spina::Current.page.materialized_path.start_with? item.materialized_path
end
```

**Comment by sarabpj** [comment]
Yes, that works 😁

**Comment by Bramjetten** [comment]
Again, thank you for working on Spina. Much appreciated 🙏 

I refactored the code a little bit and added a small test to make sure the `MenuPresenter` behaves like it should.
<sup>Our tests are *very* brittle on Github Actions and I'm not sure why... Tests are passing locally... 🤔</sup> 

Merging!

**Review by Bramjetten — APPROVED** [review]

**Comment by kfrz** [comment]
I believe this change breaks custom navigation rendering; as described in the issue I filed today - https://github.com/SpinaCMS/Spina/issues/1164. 

I am continuing investigation and will comment any further findings.

**Comment by kfrz** [comment]
Submitted a small PR that, at least for me, fixes this issue. I did *not* write any tests, because I'm feeling lazy this afternoon. Sorry. https://github.com/SpinaCMS/Spina/pull/1165

**Pull request merged**
