### PR TITLE
Add item_name to repeater part

### PR DESCRIPTION
**Pull request by Jonathan-Jacob**

### CODE REVIEW

**Comment by Jonathan-Jacob** [comment]
The >1000 line changes are because of some auto-formatting VS Code did in the locale YAMLs.

This is my first pull request from a fork, please be lenient...

**Comment by Jonathan-Jacob** [comment]
Okay, there's some stuff going on in the db. I added one migration (item names for repeater items / as opposed to repeater titles that can tell you how the whole repeater is called) and apparently it didn't go through properly. My apologies.

If you're able to clean that up a little bit, it should work. I have added the model and view files I have changed in this PR into my current project and it is working as it is supposed to.

I'll reopen now and would appreciate any feedback. I am not used to working like that but eager to learn.

**Comment by Jonathan-Jacob** [comment]
I might be wrong but I think as a first-time contributor I don't have the access rights to change anything from this commit right now. Also, I can't find the notes you added... Should I just make a new PR and close this one?

**Comment by Bramjetten** [comment]
No you can just add commits to your own branch at `Jonathan-Jacob:feature/specify-repeater-delete-buttons`, those will show up here.

My notes are in this thread.

**Comment by Jonathan-Jacob** [comment]
I haven't really gotten the knack of this workflow yet but if you decline the last two commits (both called "merge") you should end up with the old PR without locale and db changes.

**Comment by Bramjetten** [comment]
I’ll clean it up. For next time I recommend looking into git rebase for these kinds of things :)

**Comment by Jonathan-Jacob** [comment]
Thanks, will do so. I appreciate your advise!

**Review by Bramjetten — APPROVED** [review]

**Pull request merged**
