### PR TITLE
Fix account test

### PR DESCRIPTION
**Pull request by vanillaHafer**
### Context

On a recent PR for adding ancestry into custom_pages, there was a failing test.

### Changes proposed in this pull request

These changes are to fix that test, and add a default setting for the Page factory

### CODE REVIEW

**Review by Bramjetten — APPROVED** [review]

**Comment by Bramjetten** [comment]
It still fails?

**Comment by mattpolito** [comment]
@Bramjetten That's a webdriver failure. You may want to force a re-run.

**Comment by vanillaHafer** [comment]
The "flicker" around the first test failing was due to comparing Page objects and their json_attributes not being guaranteed to be in the same order. I handled that by just comparing object ids.

The 2 most recent test fails are due to the web driver issue.

**Comment by Bramjetten** [comment]
I'm also seeing intermittent web driver issues on other projects. Looks like something changed over there.

**Pull request merged**
