### PR TITLE
Bump Mobility to 1.0.0

### PR DESCRIPTION
**Pull request by shioyama**
### Context

I'm working on releasing a 1.0 of Mobility, which requires changes to configuration. Currently there's a 1.0.0.beta pre-release version, and I'd like to see how Spina tests run with this version and updated configuration.

### Changes proposed in this pull request

Bump gem version and Mobility configs. Otherwise nothing should change :crossed_fingers: 

### Guidance to review

Bumping Mobility would require applications to also bump their configs. Not sure how that would work.

### CODE REVIEW

**Comment by shioyama** [comment]
The tests seem to pass for me locally, not sure why Travis isn't running them.

I notice the current version is in alpha, could these changes maybe go into v2.0.0.beta ? Existing will need to update their Mobility configs (like the changes here).

**Comment by Bramjetten** [comment]
Excellent timing Chris! We are in the process of making some breaking changes to the underlying structure of Spina’s content with v2. We can definitely add a new mobility config.

**Comment by shioyama** [comment]
That's great to hear! We can do a Spina/Mobility joint release :tada:

**Comment by shioyama** [comment]
Seems like Travis builds are not being triggered...

**Review by Bramjetten — APPROVED** [review]

**Comment by Bramjetten** [comment]
I have no clue why, but Travis doesn't see this PR: https://travis-ci.com/github/SpinaCMS/Spina/pull_requests

The other PR's show up just fine

**Comment by shioyama** [comment]
I would suspect you maybe ran out of "credits"? See: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

I'd really like to see a passing test before merging... :sweat_smile:

**Comment by Bramjetten** [comment]
Sounds like we need to migrate to Github Actions!

**Comment by shioyama** [comment]
Bumped Mobility to 1.0.0 since it was released :tada:

**Comment by shioyama** [comment]
Shall I merge this? :sweat_smile:

**Comment by keymastervn** [comment]
Hmm, I am exploring Spina, hope this PR is going to be merged soon because current master is incompatiable already.
```ruby
# Gemfile

gem 'spina'
gem 'mobility', '~> 0.8.9'
```

**Pull request merged**
