### PR TITLE
Search in Media Library

### PR DESCRIPTION
**Pull request by noahsettersten**
### Context

We've had a client ask before about whether they can search within the media library to find uploaded items. I've experimented a bit with adding a simple search input in the header there to allow filtering by filename.

Here's a video demo of the UI for this PR: https://www.loom.com/share/52e45ba749404711b59593e0473b8b4a

### Changes proposed in this pull request

In this pull request, I've added a search bar to the tabs within the Media Library at the top right. Typing text and pressing enter or clicking Search filters the list to only those media library items that contain the search text.

### Guidance to review

Using the feature is fairly straightforward:
1. Log in to the Spina admin panel.
2. Browse to the Media Library.
3. Enter a filename in the search box at the top-right and confirm that the list of files is filtered as expected.
4. Click the "X" icon to clear the search and restore the full list.

### Questions

- Does this feature make sense within Spina core? I can see it being helpful for finding existing library files, but those files are not always named clearly for searching.
- Any thoughts on the UI? I'm not sure what the best placement for the searching UI should be. Perhaps right-aligned beneath the action buttons could work well also.

I'm open to any suggestions or ideas 👍 If this is a helpful feature, I'd be open to adding the ability to search the main list of Spina pages as well.

### CODE REVIEW

**Comment by noahsettersten** [comment]
I added a basic system test for this change, but I was unable to get the system tests working in my local development environment. I manually added a `Spina::Account` record to the test database set to the `"demo"` theme as that appeared to be necessary here.

Instead of completing successfully, the system tests hang for some time before throwing a `Net::ReadTimeout` error. This appears to happen visiting the initial login page on line 11 of `application_system_test_case.rb`. I wonder whether the test server is not responding for some reason. I'm able to run `RAILS_ENV bundle exec rails server` without issue outside of the test suite after creating the `Spina::Account` record though.

Outside of the system test, I'm open to other ideas for adding tests as well. I could perhaps create an integration test in place of this system test, if that's preferred.

**Comment by Bramjetten** [comment]
I really like this!

Couple of notes:
- Would love to also add this to the modal UI when selecting images elsewhere
- I think we can move the has_one_attached method and with_filename scope into a concern 
- I feel searching should happen instantly, without having to submit the form manually
- The search input already includes a native "x"-button in Safari for me, there's two overlapping now

Cool if I add commits to your branch?

**Comment by Bramjetten** [comment]
I played around with your branch and sprinkled some Hotwire on top:

https://user-images.githubusercontent.com/423116/216839055-ffcbdece-0e69-45c7-afd4-406a41bdcdbe.mov

**Comment by Bramjetten** [comment]
Another sketch with a subtle UI:

https://user-images.githubusercontent.com/423116/216839501-9ccad3fe-1f28-4af9-ab11-16f7db263418.mov

**Comment by Bramjetten** [comment]
Maybe it's better to put it here instead though:
CleanShot 2023-02-05 at 20 12 11@2x

**Comment by Bramjetten** [comment]
CleanShot 2023-02-07 at 10 06 15@2x


CleanShot 2023-02-07 at 10 06 31@2x

**Comment by Bramjetten** [comment]
https://user-images.githubusercontent.com/423116/217218220-05090980-6ac6-4f4f-abbb-175604b6fd8b.mov

**Comment by noahsettersten** [comment]
@Bramjetten You've taken this in a great direction; I appreciate the ideas and work you built further! Since you've opened a new PR to keep this moving, I'll close out this one in favor of your newer work in #1192.

**Pull request closed without merging**
